### PR TITLE
make experiment name optional

### PR DESCRIPTION
**Pull request by jkeroes**
Coverage shows 100% on my machine, too.

### CODE REVIEW

**Comment by lancew** [comment]
You'll have to teach me how TestingMania tests the t/example_from_pod.t? :-)
I'm not wedded to the file, but talk me through why delting is good idea?

**Comment by jkeroes** [comment]
It's faster this way. Basically, the tests break down into two sets: those
we should run before release and those that users should run before install.

The former set is testable with dzil. From `dzil help test`:

--all                    enables the RELEASE_TESTING,
                        AUTOMATED_TESTING, EXTENDED_TESTING and
                        AUTHOR_TESTING env variables

And here's what it looks like:

 ❯❯ dzil test --all
Smartmatch is experimental at
/Library/Perl/5.18/Dist/Zilla/Plugin/PrereqsClean.pm line 186, <GEN0> line
19.
[DZ] building distribution under .build/A0jhyJZ8Zj for installation
[DZ] beginning to build Scientist
[DZ] guessing dist's main_module is lib/Scientist.pm
[GitHub::Meta] Getting GitHub repository info
[DZ] writing Scientist in .build/A0jhyJZ8Zj
Checking if your kit is complete...
Looks good
Generating a Unix-style Makefile
Writing Makefile for Scientist
Writing MYMETA.yml and MYMETA.json
cp lib/Scientist.pm blib/lib/Scientist.pm
cp lib/Scientist.pod blib/lib/Scientist.pod
PERL_DL_NONLAZY=1 "/usr/bin/perl" "-MExtUtils::Command::MM"
"-MTest::Harness" "-e" "undef *Test::Harness::Switches; test_harness(0,
'blib/lib', 'blib/arch')" t/*.t
t/00-compile.t ....... ok
t/complex_data.t ..... ok
t/context.t .......... ok
t/enabled.t .......... ok
t/experiment_name.t .. ok
t/publish.t .......... ok
t/random_order.t ..... ok
t/scientist.t ........ ok
t/wantarray.t ........ ok
All tests successful.
Files=9, Tests=27,  2 wallclock secs ( 0.05 usr  0.03 sys +  1.49 cusr
 0.26 csys =  1.83 CPU)
Result: PASS
xt/author/critic.t ............ ok
xt/author/eol.t ............... ok
xt/author/mojibake.t .......... ok
xt/author/no-tabs.t ........... 1/?
#   Failed test 'No tabs in 't/random_order.t' on line 11'
#   at xt/author/no-tabs.t line 26.

#   Failed test 'No tabs in 't/scientist.t' on line 26'
#   at xt/author/no-tabs.t line 26.
# Looks like you failed 2 tests of 14.
xt/author/no-tabs.t ........... Dubious, test returned 2 (wstat 512, 0x200)
Failed 2/14 subtests
xt/author/pod-coverage.t ...... ok
xt/author/pod-syntax.t ........ ok
xt/author/test-version.t ...... ok
xt/release/cpan-changes.t ..... ok
xt/release/dist-manifest.t .... 1/4 # Unable to parse MANIFEST.SKIP file:
# No such file or directory
# Using default skip data from ExtUtils::Manifest 1.70
# MANIFEST and MANIFEST.SKIP have circular dependencies:
# cover_db/-usr-local-bin-prove--branch.html
# cover_db/-usr-local-bin-prove--subroutine.html
# cover_db/-usr-local-bin-prove.html
# cover_db/cover.14
# cover_db/cover.css
# cover_db/coverage.html
# cover_db/digests
# cover_db/lib-Scientist-pm--branch.html
# cover_db/lib-Scientist-pm--subroutine.html
# cover_db/lib-Scientist-pm.html
# cover_db/structure/0af459f67b05611c7ef07d9ac2710643
# cover_db/structure/0ec01cec2476869e81a5b2fffaaedaff
# cover_db/structure/21e73f8108011cf2b4a36ecf75a298b9
# cover_db/structure/5c3cac2965e35b8c5290fe07d79047c5
# cover_db/structure/8082cd6297659de4ffdbdbd0f1ea946d
# cover_db/structure/8a8a4ab507c9073516f2ce3fb0e0a523
# cover_db/structure/ad6c64e5788956c8aa6790f4459ff29b
# cover_db/structure/c2640be30b615ab9f32cca88cf4e15a3
# cover_db/structure/c3e54acabbd0a8db3579079203170ecc
# cover_db/structure/ff11748ff0665bac4f351f1ba905fe79
# cover_db/t-complex_data-t--branch.html
# cover_db/t-complex_data-t--subroutine.html
# cover_db/t-complex_data-t.html
# cover_db/t-context-t--branch.html
# cover_db/t-context-t--subroutine.html
# cover_db/t-context-t.html
# cover_db/t-enabled-t--branch.html
# cover_db/t-enabled-t--subroutine.html
# cover_db/t-enabled-t.html
# cover_db/t-experiment_name-t--subroutine.html
# cover_db/t-experiment_name-t.html
# cover_db/t-publish-t--branch.html
# cover_db/t-publish-t--subroutine.html
# cover_db/t-publish-t.html
# cover_db/t-random_order-t--condition.html
# cover_db/t-random_order-t--subroutine.html
# cover_db/t-random_order-t.html
# cover_db/t-scientist-t--branch.html
# cover_db/t-scientist-t--subroutine.html
# cover_db/t-scientist-t.html
# cover_db/t-wantarray-t--branch.html
# cover_db/t-wantarray-t--subroutine.html
# cover_db/t-wantarray-t.html
# t/cover_db/digests
# t/cover_db/runs/1459534693.23806.07446/cover.14
# t/cover_db/structure/8a8a4ab507c9073516f2ce3fb0e0a523

#   Failed test 'No files are in both MANIFEST and MANIFEST.SKIP'
#   at xt/release/dist-manifest.t line 8.
# Looks like you failed 1 test of 4.
xt/release/dist-manifest.t .... Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/4 subtests
xt/release/distmeta.t ......... ok
xt/release/kwalitee.t ......... ok
xt/release/minimum-version.t .. ok
xt/release/pod-linkcheck.t .... 1/2
#   Failed test 'LinkCheck test for blib/lib/Scientist.pod'
#   at /Library/Perl/5.18/Test/Pod/LinkCheck.pm line 284.
# Erroneous links:
#  * blib/lib/Scientist.pod:77:11 - Unknown link type(pod) to()
section(Functions/name()) - section doesn't exist!
# Looks like you failed 1 test of 2.
xt/release/pod-linkcheck.t .... Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/2 subtests
xt/release/portability.t ...... 1/1
#   Failed test 'File names portability'
#   at xt/release/portability.t line 12.
# These files does not respect the portable filename characters
# as defined by ANSI C and perlport:
#    cover_db/-usr-local-bin-prove--branch.html
#    cover_db/-usr-local-bin-prove--subroutine.html
#    cover_db/-usr-local-bin-prove.html
#
# Looks like you failed 1 test of 1.
xt/release/portability.t ...... Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/1 subtests
xt/release/synopsis.t ......... ok
xt/release/unused-vars.t ...... ok

Test Summary Report
-------------------
xt/author/no-tabs.t         (Wstat: 512 Tests: 14 Failed: 2)
  Failed tests:  12-13
  Non-zero exit status: 2
xt/release/dist-manifest.t  (Wstat: 256 Tests: 4 Failed: 1)
  Failed test:  4
  Non-zero exit status: 1
xt/release/pod-linkcheck.t  (Wstat: 256 Tests: 2 Failed: 1)
  Failed test:  2
  Non-zero exit status: 1
xt/release/portability.t    (Wstat: 256 Tests: 1 Failed: 1)
  Failed test:  1
  Non-zero exit status: 1
Files=16, Tests=78,  5 wallclock secs ( 0.10 usr  0.12 sys +  3.58 cusr
 0.67 csys =  4.47 CPU)
Result: FAIL
[RunExtraTests] Fatal errors in xt tests
[RunExtraTests] Fatal errors in xt tests at
/Library/Perl/5.18/darwin-thread-multi-2level/Moose/Meta/Method/Delegation.pm
line 110.

(I'll have a new patchset up in a few that addresses these).

**Comment by jkeroes** [comment]
I didn't answer your question, did I?

Let's back up.

The TestingMania Bundle pulls in a bunch of other stuff. The module we're
interested in here is
https://metacpan.org/pod/Dist::Zilla::Plugin::Test::Synopsis which really
runs https://metacpan.org/pod/Test::Synopsis . That module's job is to make
sure that the code in a SYNOPSIS passes a syntax check.

You can see that it ran—and passed—in the output above:

xt/release/synopsis.t ......... ok

So, this file deletion has two benefits:

   1. it passes the DRY Principle.
   2. we no longer have to keep the test file and the SYNOPSIS in sync.

I can't remember offhand if cpanm(1) or cpan(1) runs xt/ tests when
installing modules. If they didn't, then it's... not worse, but if they do,
then we just saved the user some time; a third benefit.

**Comment by lancew** [comment]
https://metacpan.org/pod/Test::Synopsis is very cool.

**Pull request merged**
